version: '3'
services:
  user-service:
    build: ./UserService
    ports:
      - "5001:5000"
  product-service:
    build: ./ProductService
    ports:
      - "5002:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service

