version: '3.8'
services:
  user-service:
    build: ./UserService
    ports:
      - "5000:5000"
    networks:
      - microservices

  product-service:
    build: ./ProductService
    ports:
      - "5000:5000"
    networks:
      - microservices

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices

networks:
  microservices:
